# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UnistoreCli < Formula
  desc ""
  homepage "https://github.com/unistorecom/cli"
  version "0.0.7"

  on_macos do
    url "https://github.com/unistorecom/cli/releases/download/0.0.7/cli_0.0.7_darwin_all.tar.gz", using: CurlDownloadStrategy
    sha256 "c441e49e1181c838c43cde029a6fb2d0543b8f8919c9979b765c309409eb0ef5"

    def install
      bin.install "cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/unistorecom/cli/releases/download/0.0.7/cli_0.0.7_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "76901761f02709ec943ea332dc9c9028b68f1e06d8eef10cde1efe7ed3a843bf"

      def install
        bin.install "cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/unistorecom/cli/releases/download/0.0.7/cli_0.0.7_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "3a52da0795ad5f39a464ebbe442b21d67adcf963002833de385d4cd1e9366ccb"

      def install
        bin.install "cli"
      end
    end
  end
end
