# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UnistoreCli < Formula
  desc ""
  homepage "https://github.com/unistorecom/cli"
  version "0.0.53"

  on_macos do
    url "https://cdn.dev.unistore.tech/public/cli/0.0.53/cli_0.0.53_darwin_all.tar.gz", using: CurlDownloadStrategy
    sha256 "88d2734472e2ca17cb3058c9007104b191a314f8a933d341eaa5b0372e5555fd"

    def install
      bin.install "cli" => "unistore"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://cdn.dev.unistore.tech/public/cli/0.0.53/cli_0.0.53_linux_amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "e0f091742262ea0199bf4952e79ae9aeac6890dba98d0611972ca4c15784e3d9"

        def install
          bin.install "cli" => "unistore"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://cdn.dev.unistore.tech/public/cli/0.0.53/cli_0.0.53_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "e5ab15ff47d07c8d0f57534d04d839e3d169264f2ad12e0822af162f38769eac"

        def install
          bin.install "cli" => "unistore"
        end
      end
    end
  end
end
